name: Build NuGet Package

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  DOTNET_EnableDiagnostics: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore src/GitLabSourceLink/GitLabSourceLink.csproj

      - name: Build
        run: dotnet build -c Release src/GitLabSourceLink/GitLabSourceLink.csproj --no-restore

      - name: Pack NuGet package
        run: dotnet pack -c Release src/GitLabSourceLink/GitLabSourceLink.csproj -o nuget-packages --no-build

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: nuget-packages/*.nupkg
          retention-days: 30
